name: Semantic Versioning Label Check

on:
  pull_request:
    branches: [main]

jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check for semantic versioning label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          if echo "$LABELS" | grep -qE "major|minor|patch"; then
            echo "Semantic versioning label found."
          else
            echo "No semantic versioning label found. Please add a 'major', 'minor', or 'patch' label to this PR."
            exit 1
          fi
